### ISSUE TITLE
How to use the "onChange" function

### ISSUE THREAD

**Issue by rodrigoAbril** [matt-sanders/vue-formly-bootstrap#1]
how can I use the onChange function i have tried calling it like:
```
type: "select",
options: selectOptionsList,
templateOptions : {
    label           : "text",
    onChange  :  functionX(),
}
```
but weirdly the functionX() only runs on load instead of on change

**Comment by matt-sanders** [comment]
Sorry @rodrigoAbril just saw this, but you got my message on gitter so I'll close this now.
